[config]

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/dank-material.theme'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.telegram]
input_path = '~/.config/matugen/templates/telegram.tdesktop-theme'
output_path = '~/.config/telegram-theme/colors.tdesktop-theme'

[templates.mailspring]
input_path = '~/.config/matugen/templates/mailspring.less'
output_path = '~/.config/Mailspring/packages/dank-material/styles/ui-variables.less'
