# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-label/nixos";
      neededForBoot = true;
      fsType = "btrfs";
      options = [ "subvol=persist" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/wingej0/Vault" =
    { device = "/dev/disk/by-label/vault";
      fsType = "btrfs";
      options = [ "subvol=vault" "compress=zstd" ];
    };

  fileSystems."/home/wingej0/Dev" =
    { device = "/dev/disk/by-label/vault";
      fsType = "btrfs";
      options = [ "subvol=dev" "compress=zstd" ];
    };

  fileSystems."/home/wingej0/Music" =
    { device = "/dev/disk/by-label/vault";
      fsType = "btrfs";
      options = [ "subvol=music" "compress=zstd" ];
    };

  fileSystems."/home/wingej0/Pictures" =
    { device = "/dev/disk/by-label/vault";
      fsType = "btrfs";
      options = [ "subvol=pictures" "compress=zstd" ];
    };

  fileSystems."/home/wingej0/Documents" =
    { device = "/dev/disk/by-label/vault";
      fsType = "btrfs";
      options = [ "subvol=documents" "compress=zstd" ];
    };

  fileSystems."/home/wingej0/Videos" =
    { device = "/dev/disk/by-label/vault";
      fsType = "btrfs";
      options = [ "subvol=videos" "compress=zstd" ];
    };

  fileSystems."/var/lib/immich" =
    { device = "/dev/disk/by-label/vault";
      fsType = "btrfs";
      options = [ "subvol=immich" "compress=zstd" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/swap"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp13s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
